/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_practice_lang_system_jni_c_JNIExample */

#ifndef _Included_com_example_practice_lang_system_jni_c_JNIExample
#define _Included_com_example_practice_lang_system_jni_c_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_practice_lang_system_jni_c_JNIExample
 * Method:    returnInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_practice_lang_system_jni_c_JNIExample_returnInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_practice_lang_system_jni_c_JNIExample
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_practice_lang_system_jni_c_JNIExample_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
