/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_practice_jvm_jni_JNIExample */

#ifndef _Included_com_example_practice_jvm_jni_JNIExample
#define _Included_com_example_practice_jvm_jni_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_practice_jvm_jni_JNIExample
 * Method:    returnInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_practice_jvm_jni_JNIExample_returnInt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
